version: '3.8'

services:
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example_password
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.3-fpm
    volumes:
      - wordpress_data:/var/www/html
      - ./themes:/var/www/html/wp-content/themes # Mount local themes directory
      - ./plugins:/var/www/html/wp-content/plugins # Mount local plugins directory
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress-network

  nginx:
    image: nginx:latest
    ports:
      - "8660:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    networks:
      - wordpress-network

volumes:
  db_data: {}
  wordpress_data: {}

networks:
  wordpress-network:
    driver: bridge
